version: '3'
services:
  es:
    image: elasticsearch:2.4
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
  dj:
    build: .
    links:
      - es
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/share/django
