# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import simple_elasticsearch.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('content', models.TextField()),
            ],
            bases=(models.Model, simple_elasticsearch.mixins.ElasticsearchTypeMixin),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('rss_url', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djesapp.Blog'),
        ),
    ]
